// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToursimPackageService.Models;

#nullable disable

namespace ToursimPackageService.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToursimPackageService.Model.TotalDaysDescription", b =>
                {
                    b.Property<int>("TotalDaysDescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TotalDaysDescriptionId"));

                    b.Property<string>("DayDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InclusionId")
                        .HasColumnType("int");

                    b.Property<string>("TourSpotName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TotalDaysDescriptionId");

                    b.HasIndex("InclusionId");

                    b.ToTable("TotalDaysDescriptions");
                });

            modelBuilder.Entity("ToursimPackageService.Models.Inclusion", b =>
                {
                    b.Property<int>("InclusionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InclusionId"));

                    b.Property<string>("Accommodation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Meals")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalDays")
                        .HasColumnType("int");

                    b.Property<int>("TotalNights")
                        .HasColumnType("int");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.Property<string>("Transfer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("InclusionId");

                    b.HasIndex("TourId")
                        .IsUnique();

                    b.ToTable("Inclusion");
                });

            modelBuilder.Entity("ToursimPackageService.Models.Tours", b =>
                {
                    b.Property<int>("TourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TourId"));

                    b.Property<int>("MaxCount")
                        .HasColumnType("int");

                    b.Property<string>("TourLocationCity")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TourLocationCountry")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TourLocationState")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TourName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("TourPrice")
                        .HasColumnType("real");

                    b.Property<string>("TourSpecialty")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TravelAgentId")
                        .HasColumnType("int");

                    b.HasKey("TourId");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("ToursimPackageService.Model.TotalDaysDescription", b =>
                {
                    b.HasOne("ToursimPackageService.Models.Inclusion", "Inclusion")
                        .WithMany("TotalDaysDescriptions")
                        .HasForeignKey("InclusionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inclusion");
                });

            modelBuilder.Entity("ToursimPackageService.Models.Inclusion", b =>
                {
                    b.HasOne("ToursimPackageService.Models.Tours", "Tour")
                        .WithOne("Inclusion")
                        .HasForeignKey("ToursimPackageService.Models.Inclusion", "TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("ToursimPackageService.Models.Inclusion", b =>
                {
                    b.Navigation("TotalDaysDescriptions");
                });

            modelBuilder.Entity("ToursimPackageService.Models.Tours", b =>
                {
                    b.Navigation("Inclusion");
                });
#pragma warning restore 612, 618
        }
    }
}
