// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToursimBookingService.Models;

#nullable disable

namespace ToursimBookingService.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230802095954_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ToursimBookingService.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"), 1L, 1);

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NoOfPersons")
                        .HasColumnType("int");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.Property<int>("TravellerId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("ToursimBookingService.Models.BookingUser", b =>
                {
                    b.Property<int>("BookingUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingUserId"), 1L, 1);

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("BookingUserEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookingUserGender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookingUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookingUserPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookingUserId");

                    b.HasIndex("BookingId");

                    b.ToTable("BookingUsers");
                });

            modelBuilder.Entity("ToursimBookingService.Models.BookingUser", b =>
                {
                    b.HasOne("ToursimBookingService.Models.Booking", "Booking")
                        .WithMany("BookingUsers")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("ToursimBookingService.Models.Booking", b =>
                {
                    b.Navigation("BookingUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
